version: 2
updates:
  # raise PRs for gem updates
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    groups:
      ruby:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "*"
    ignore:
      # see https://github.com/rubyjs/libv8-node/issues/60
      - dependency-name: "libv8-node"
      # see https://github.com/rubyjs/mini_racer/issues/344
      - dependency-name: "mini_racer"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
    open-pull-requests-limit: 10
