---

on:
  - pull_request

name: CI

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        scandir: './bin'

  rubocop:
    name: 'RuboCop'
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake rubocop

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup config
      run: mv config/hdm.yml{.template,}
    - name: Run tests
      run: bundle exec rake test:all

  build_docker_image:
    name: 'Built test Docker image'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0
        with:
          context: .
          push: false
