---
on:
  - pull_request

name: 🚦 CI

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        scandir: './bin'

  rubocop:
    name: 'RuboCop'
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake rubocop

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup config
      run: mv config/hdm.yml{.template,}
    - name: Run tests
      run: bundle exec rake test:all

  build_container_image_arm64:
    name: 'Built test container image for ARM64'
    runs-on: ubuntu-24.04-arm
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Add VERSION file
        run: |
          git describe > VERSION

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: 'ci/hdm:${{ github.sha }}'
          push: false
          platforms: linux/arm64

  build_container_image_x86:
    name: 'Built test container image on x86'
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Add VERSION file
        run: |
          git describe > VERSION

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: 'ci/hdm:${{ github.sha }}'
          push: false

  tests:
    needs:
      - shellcheck
      - rubocop
      - unit_tests
      - build_container_image_arm64
      - build_container_image_x86
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed

  dependabot:
    permissions:
      contents: write
    name: 'Dependabot auto-merge'
    needs:
      - tests
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.3.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
