---

on:
  - pull_request

name: CI

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        scandir: './bin'
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake rubocop
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup config
      run: mv config/hdm.yml{.template,}
    - name: Install webpacker
      run: bundle exec rake webpacker:install
    - name: Generate assets
      run: bundle exec rake webpacker:compile
    - name: Verify assets
      run: bundle exec rake webpacker:verify_install
    - name: Run tests
      run: bundle exec rake test:all
